import { CompanyProfile, Invoice, ClientVendor, Expense, ExpenseCategory } from './invoice';

export const DEFAULT_ZOOLYUM_PROFILE: CompanyProfile = {
  name: 'Your Company',
  tagline: 'Brand Strategy & Digital Innovation',
  logoUrl: '',
  brandColor: '#ea580c',
  authorizedSignerName: 'John Dewey',
  authorizedSignerTitle: 'Authorized Signature',
  signatureImageUrl: '',
  email: 'contact@yourcompany.com',
  phone: '01601000950',
  address: 'Mirpur 10, Dhaka-1216',
  city: 'Dhaka',
  country: 'Bangladesh',
  taxId: 'BIN: 004928194-0101',
  website: 'https://yourcompany.com',
  defaultPaymentDetails: {
    method: 'bank',
    bankName: 'City Bank PLC',
    accountName: 'Your Company Ltd.',
    accountNumber: '1102938475001',
    branch: 'Mirpur Branch, Dhaka',
    routingNumber: '225261738',
    mobileWalletNumber: '01601000950 (bKash / Nagad Merchant)',
    paymentNote: 'Please use Invoice # as payment reference.',
  },
  defaultCurrency: 'BDT',
  defaultNotes: 'Thank you for choosing Your Company! We appreciate your business and collaboration on building exceptional brand experiences.',
  defaultTerms: 'Payment is due within 15 days of invoice date. Late payments may be subject to a 2% monthly service fee.',
};

export const INITIAL_CLIENTS: ClientVendor[] = [
  {
    id: 'client-1',
    name: 'Apex Footwear Ltd.',
    company: 'Apex Group',
    email: 'accounts@apexfootwear.com',
    phone: '+880 1711-234567',
    address: 'Apex Centre, 76/1 Bir Uttam A.K. Khandakar Road, Mohakhali C/A',
    city: 'Dhaka',
    country: 'Bangladesh',
    taxId: 'BIN-001294819',
    totalBilled: 385000,
    invoicesCount: 3,
    notes: 'Key enterprise client - Brand identity and e-commerce UI revamp.',
  },
  {
    id: 'client-2',
    name: 'Shwapno Superstores',
    company: 'ACI Logistics Ltd.',
    email: 'billing@shwapno.com.bd',
    phone: '+880 1819-876543',
    address: 'Novo Tower, Level-8, 270 Tejgaon I/A',
    city: 'Dhaka',
    country: 'Bangladesh',
    taxId: 'BIN-003847291',
    totalBilled: 520000,
    invoicesCount: 4,
    notes: 'Retail campaign design & omnichannel digital marketing assets.',
  },
  {
    id: 'client-3',
    name: 'Pathao Technologies Ltd.',
    company: 'Pathao Inc.',
    email: 'finance@pathao.com',
    phone: '+880 1912-998877',
    address: 'House 45, Road 11, Block H, Banani',
    city: 'Dhaka',
    country: 'Bangladesh',
    taxId: 'BIN-008273645',
    totalBilled: 275000,
    invoicesCount: 2,
    notes: 'Ride-sharing app user experience audit and brand positioning guideline.',
  },
  {
    id: 'client-4',
    name: 'Chaldal Grocery Services',
    company: 'Chaldal Bangladesh',
    email: 'vendor@chaldal.com',
    phone: '+880 1611-334455',
    address: 'Plot 12, Block C, Uttara Sector 3',
    city: 'Dhaka',
    country: 'Bangladesh',
    taxId: 'BIN-009182736',
    totalBilled: 195000,
    invoicesCount: 2,
    notes: 'Packaging design and social media visual identity pack.',
  },
  {
    id: 'client-5',
    name: 'Dhaka Motors & Logistics',
    company: 'Dhaka Motors Corp',
    email: 'info@dhakamotors.com.bd',
    phone: '+880 1713-556677',
    address: 'Kakrail Commercial Area',
    city: 'Dhaka',
    country: 'Bangladesh',
    taxId: 'BIN-005544332',
    totalBilled: 140000,
    invoicesCount: 1,
    notes: 'New vehicle line launch branding and video graphics.',
  },
  {
    id: 'client-6',
    name: 'Grameen Digital Innovation Lab',
    company: 'Grameen Telecom Trust',
    email: 'partner.relations@grameen.org',
    phone: '+880 1715-001122',
    address: 'Grameen Bank Bhaban, Mirpur 2',
    city: 'Dhaka',
    country: 'Bangladesh',
    taxId: 'BIN-002233445',
    totalBilled: 460000,
    invoicesCount: 3,
    notes: 'Social enterprise branding and web portal redesign project.',
  }
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-2026-001',
    invoiceNumber: 'ZOO-2026-001',
    issueDate: '2026-08-10',
    dueDate: '2026-08-25',
    status: 'paid',
    client: {
      id: 'client-1',
      name: 'Apex Footwear Ltd.',
      company: 'Apex Group',
      email: 'accounts@apexfootwear.com',
      phone: '+880 1711-234567',
      address: 'Apex Centre, 76/1 Bir Uttam A.K. Khandakar Road, Mohakhali C/A, Dhaka',
      taxId: 'BIN-001294819',
    },
    company: DEFAULT_ZOOLYUM_PROFILE,
    currency: {
      symbol: '৳',
      code: 'BDT',
      name: 'Bangladeshi Taka',
    },
    items: [
      {
        id: 'item-1',
        description: 'Complete Brand Identity & Typography Guidelines (Phase 1)',
        quantity: 1,
        unitPrice: 120000,
        amount: 120000,
      },
      {
        id: 'item-2',
        description: 'E-commerce UI/UX Design System (Figma Component Library)',
        quantity: 1,
        unitPrice: 95000,
        amount: 95000,
      },
      {
        id: 'item-3',
        description: 'Interactive Design Prototyping & User Testing (2 rounds)',
        quantity: 2,
        unitPrice: 20000,
        amount: 40000,
      }
    ],
    subtotal: 255000,
    taxRate: 5,
    taxAmount: 12750,
    discountRate: 0,
    discountAmount: 0,
    shippingFee: 0,
    totalAmount: 267750,
    paidAmount: 267750,
    balanceDue: 0,
    paymentDetails: DEFAULT_ZOOLYUM_PROFILE.defaultPaymentDetails,
    notes: 'Milestone 1 payment completed successfully via City Bank PLC Wire Transfer.',
    terms: DEFAULT_ZOOLYUM_PROFILE.defaultTerms,
    templateStyle: 'zoolyum-dark',
    createdAt: '2026-08-10T10:30:00.000Z',
    updatedAt: '2026-08-14T14:15:00.000Z',
  },
  {
    id: 'inv-2026-002',
    invoiceNumber: 'ZOO-2026-002',
    issueDate: '2026-08-14',
    dueDate: '2026-08-29',
    status: 'pending',
    client: {
      id: 'client-2',
      name: 'Shwapno Superstores',
      company: 'ACI Logistics Ltd.',
      email: 'billing@shwapno.com.bd',
      phone: '+880 1819-876543',
      address: 'Novo Tower, Level-8, 270 Tejgaon I/A, Dhaka',
      taxId: 'BIN-003847291',
    },
    company: DEFAULT_ZOOLYUM_PROFILE,
    currency: {
      symbol: '৳',
      code: 'BDT',
      name: 'Bangladeshi Taka',
    },
    items: [
      {
        id: 'item-201',
        description: 'Festival Campaign Strategy & Creative Direction for Autumn 2026',
        quantity: 1,
        unitPrice: 180000,
        amount: 180000,
      },
      {
        id: 'item-202',
        description: 'Social Media High-Conversion Visual Asset Pack (30 designs)',
        quantity: 30,
        unitPrice: 3500,
        amount: 105000,
      },
      {
        id: 'item-203',
        description: 'Motion Graphic Promo Video (30s 4K Reels/Shorts)',
        quantity: 2,
        unitPrice: 35000,
        amount: 70000,
      }
    ],
    subtotal: 355000,
    taxRate: 5,
    taxAmount: 17750,
    discountRate: 5,
    discountAmount: 17750,
    shippingFee: 0,
    totalAmount: 355000,
    paidAmount: 100000,
    balanceDue: 255000,
    paymentDetails: DEFAULT_ZOOLYUM_PROFILE.defaultPaymentDetails,
    notes: 'Advance ৳100,000 paid on contract signing. Remainder due on final asset delivery.',
    terms: DEFAULT_ZOOLYUM_PROFILE.defaultTerms,
    templateStyle: 'modern-orange',
    createdAt: '2026-08-14T09:00:00.000Z',
    updatedAt: '2026-08-14T09:00:00.000Z',
  },
  {
    id: 'inv-2026-003',
    invoiceNumber: 'ZOO-2026-003',
    issueDate: '2026-07-15',
    dueDate: '2026-07-30',
    status: 'overdue',
    client: {
      id: 'client-3',
      name: 'Pathao Technologies Ltd.',
      company: 'Pathao Inc.',
      email: 'finance@pathao.com',
      phone: '+880 1912-998877',
      address: 'House 45, Road 11, Block H, Banani, Dhaka',
      taxId: 'BIN-008273645',
    },
    company: DEFAULT_ZOOLYUM_PROFILE,
    currency: {
      symbol: '৳',
      code: 'BDT',
      name: 'Bangladeshi Taka',
    },
    items: [
      {
        id: 'item-301',
        description: 'Strategic Brand Audit & Rider Experience Optimization Report',
        quantity: 1,
        unitPrice: 150000,
        amount: 150000,
      },
      {
        id: 'item-302',
        description: 'Design Sprint Workshop (2 Days with Executive Team)',
        quantity: 2,
        unitPrice: 40000,
        amount: 80000,
      }
    ],
    subtotal: 230000,
    taxRate: 5,
    taxAmount: 11500,
    discountRate: 0,
    discountAmount: 0,
    shippingFee: 0,
    totalAmount: 241500,
    paidAmount: 0,
    balanceDue: 241500,
    paymentDetails: DEFAULT_ZOOLYUM_PROFILE.defaultPaymentDetails,
    notes: 'Reminder sent on August 5th. Awaiting final clearance from finance department.',
    terms: 'Overdue notice: Please settle at your earliest convenience.',
    templateStyle: 'zoolyum-dark',
    createdAt: '2026-07-15T11:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z',
  },
  {
    id: 'inv-2026-004',
    invoiceNumber: 'ZOO-2026-004',
    issueDate: '2026-08-05',
    dueDate: '2026-08-20',
    status: 'paid',
    client: {
      id: 'client-4',
      name: 'Chaldal Grocery Services',
      company: 'Chaldal Bangladesh',
      email: 'vendor@chaldal.com',
      phone: '+880 1611-334455',
      address: 'Plot 12, Block C, Uttara Sector 3, Dhaka',
      taxId: 'BIN-009182736',
    },
    company: DEFAULT_ZOOLYUM_PROFILE,
    currency: {
      symbol: '৳',
      code: 'BDT',
      name: 'Bangladeshi Taka',
    },
    items: [
      {
        id: 'item-401',
        description: 'Private Label Organic Products Packaging Identity (6 SKUs)',
        quantity: 6,
        unitPrice: 22000,
        amount: 132000,
      },
      {
        id: 'item-402',
        description: '3D Product Render & Mockup Visualization Pack',
        quantity: 6,
        unitPrice: 7000,
        amount: 42000,
      }
    ],
    subtotal: 174000,
    taxRate: 5,
    taxAmount: 8700,
    discountRate: 0,
    discountAmount: 0,
    shippingFee: 0,
    totalAmount: 182700,
    paidAmount: 182700,
    balanceDue: 0,
    paymentDetails: DEFAULT_ZOOLYUM_PROFILE.defaultPaymentDetails,
    notes: 'Paid in full via bKash Merchant Gateway on 12 August 2026.',
    terms: DEFAULT_ZOOLYUM_PROFILE.defaultTerms,
    templateStyle: 'modern-orange',
    createdAt: '2026-08-05T14:20:00.000Z',
    updatedAt: '2026-08-12T16:00:00.000Z',
  },
  {
    id: 'inv-2026-005',
    invoiceNumber: 'ZOO-2026-005',
    issueDate: '2026-08-18',
    dueDate: '2026-09-02',
    status: 'draft',
    client: {
      id: 'client-5',
      name: 'Dhaka Motors & Logistics',
      company: 'Dhaka Motors Corp',
      email: 'info@dhakamotors.com.bd',
      phone: '+880 1713-556677',
      address: 'Kakrail Commercial Area, Dhaka',
      taxId: 'BIN-005544332',
    },
    company: DEFAULT_ZOOLYUM_PROFILE,
    currency: {
      symbol: '৳',
      code: 'BDT',
      name: 'Bangladeshi Taka',
    },
    items: [
      {
        id: 'item-501',
        description: 'Automotive Showcase Landing Page Development & WebGL 360 viewer',
        quantity: 1,
        unitPrice: 110000,
        amount: 110000,
      },
      {
        id: 'item-502',
        description: 'SEO Architecture & Performance Optimization',
        quantity: 1,
        unitPrice: 30000,
        amount: 30000,
      }
    ],
    subtotal: 140000,
    taxRate: 5,
    taxAmount: 7000,
    discountRate: 0,
    discountAmount: 0,
    shippingFee: 0,
    totalAmount: 147000,
    paidAmount: 0,
    balanceDue: 147000,
    paymentDetails: DEFAULT_ZOOLYUM_PROFILE.defaultPaymentDetails,
    notes: 'Draft quote sent for client internal review and PO approval.',
    terms: DEFAULT_ZOOLYUM_PROFILE.defaultTerms,
    templateStyle: 'zoolyum-dark',
    createdAt: '2026-08-18T16:45:00.000Z',
    updatedAt: '2026-08-18T16:45:00.000Z',
  },
  {
    id: 'inv-2026-006',
    invoiceNumber: 'ZOO-2026-006',
    issueDate: '2026-08-01',
    dueDate: '2026-08-16',
    status: 'paid',
    client: {
      id: 'client-6',
      name: 'Grameen Digital Innovation Lab',
      company: 'Grameen Telecom Trust',
      email: 'partner.relations@grameen.org',
      phone: '+880 1715-001122',
      address: 'Grameen Bank Bhaban, Mirpur 2, Dhaka',
      taxId: 'BIN-002233445',
    },
    company: DEFAULT_ZOOLYUM_PROFILE,
    currency: {
      symbol: '৳',
      code: 'BDT',
      name: 'Bangladeshi Taka',
    },
    items: [
      {
        id: 'item-601',
        description: 'Annual Creative Strategy & Social Impact Storytelling Retainer (Q3)',
        quantity: 1,
        unitPrice: 350000,
        amount: 350000,
      },
      {
        id: 'item-602',
        description: 'Quarterly Impact Visual Report & Infographics (10 sets)',
        quantity: 10,
        unitPrice: 9000,
        amount: 90000,
      }
    ],
    subtotal: 440000,
    taxRate: 5,
    taxAmount: 22000,
    discountRate: 2,
    discountAmount: 8800,
    shippingFee: 0,
    totalAmount: 453200,
    paidAmount: 453200,
    balanceDue: 0,
    paymentDetails: DEFAULT_ZOOLYUM_PROFILE.defaultPaymentDetails,
    notes: 'Q3 Retainer invoiced & settled. Thank you for our ongoing partnership!',
    terms: DEFAULT_ZOOLYUM_PROFILE.defaultTerms,
    templateStyle: 'zoolyum-dark',
    createdAt: '2026-08-01T08:30:00.000Z',
    updatedAt: '2026-08-15T11:20:00.000Z',
  }
];

export const EXPENSE_CATEGORIES: {
  id: ExpenseCategory;
  label: string;
  color: string;
  bgLight: string;
  iconName: string;
}[] = [
  { id: 'marketing', label: 'Advertising & Marketing', color: '#f97316', bgLight: 'bg-orange-500/10 text-orange-600 dark:text-orange-400 border-orange-500/20', iconName: 'Megaphone' },
  { id: 'office', label: 'Office Rent & Facilities', color: '#3b82f6', bgLight: 'bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20', iconName: 'Building2' },
  { id: 'software', label: 'Software & Subscriptions (SaaS)', color: '#8b5cf6', bgLight: 'bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20', iconName: 'Laptop' },
  { id: 'salaries', label: 'Salaries & Freelancers', color: '#10b981', bgLight: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20', iconName: 'Users' },
  { id: 'utilities', label: 'Utilities, Cloud & Internet', color: '#06b6d4', bgLight: 'bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-500/20', iconName: 'Wifi' },
  { id: 'travel', label: 'Travel & Client Conveyance', color: '#eab308', bgLight: 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20', iconName: 'Car' },
  { id: 'food', label: 'Food, Team & Entertainment', color: '#ec4899', bgLight: 'bg-pink-500/10 text-pink-600 dark:text-pink-400 border-pink-500/20', iconName: 'Coffee' },
  { id: 'hardware', label: 'Hardware, Camera & Equipment', color: '#6366f1', bgLight: 'bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/20', iconName: 'Monitor' },
  { id: 'taxes', label: 'Taxes, Legal & Bank Fees', color: '#64748b', bgLight: 'bg-slate-500/10 text-slate-600 dark:text-slate-400 border-slate-500/20', iconName: 'ShieldAlert' },
  { id: 'miscellaneous', label: 'Miscellaneous Supplies', color: '#71717a', bgLight: 'bg-zinc-500/10 text-zinc-600 dark:text-zinc-400 border-zinc-500/20', iconName: 'Package' },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-2026-001',
    title: 'Figma Organization & Adobe Creative Cloud Subscription',
    category: 'software',
    amount: 18500,
    currency: { symbol: '৳', code: 'BDT', name: 'Bangladeshi Taka' },
    date: '2026-08-02',
    payeeVendor: 'Adobe & Figma Inc.',
    paymentMethod: 'card',
    status: 'paid',
    notes: 'Monthly design software licensing for creative department.',
    createdAt: '2026-08-02T10:00:00.000Z',
    updatedAt: '2026-08-02T10:00:00.000Z',
  },
  {
    id: 'exp-2026-002',
    title: 'Facebook & Meta Ads Campaign (Agency Lead Generation)',
    category: 'marketing',
    amount: 45000,
    currency: { symbol: '৳', code: 'BDT', name: 'Bangladeshi Taka' },
    date: '2026-08-06',
    payeeVendor: 'Meta Ads Global',
    paymentMethod: 'card',
    status: 'paid',
    notes: 'Sponsored B2B campaigns for brand transformation services.',
    createdAt: '2026-08-06T12:30:00.000Z',
    updatedAt: '2026-08-06T12:30:00.000Z',
  },
  {
    id: 'exp-2026-003',
    title: 'Mirpur Studio Office Rent & Service Charge',
    category: 'office',
    amount: 65000,
    currency: { symbol: '৳', code: 'BDT', name: 'Bangladeshi Taka' },
    date: '2026-08-01',
    payeeVendor: 'Green City Commercial Tower',
    paymentMethod: 'bank',
    status: 'paid',
    notes: 'August 2026 office premises rent and maintenance.',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
  },
  {
    id: 'exp-2026-004',
    title: '3D Motion Freelance Modeler (Apex Project Asset)',
    category: 'salaries',
    amount: 32000,
    currency: { symbol: '৳', code: 'BDT', name: 'Bangladeshi Taka' },
    date: '2026-08-11',
    payeeVendor: 'Tanvir Hossain (Freelancer)',
    paymentMethod: 'bkash',
    status: 'paid',
    notes: 'Payment for 3D shoe render passes and textures.',
    createdAt: '2026-08-11T16:00:00.000Z',
    updatedAt: '2026-08-11T16:00:00.000Z',
  },
  {
    id: 'exp-2026-005',
    title: 'High-speed Dedicated Fiber Internet & Server Hosting',
    category: 'utilities',
    amount: 12000,
    currency: { symbol: '৳', code: 'BDT', name: 'Bangladeshi Taka' },
    date: '2026-08-05',
    payeeVendor: 'Dot Internet & Digital Ocean',
    paymentMethod: 'nagad',
    status: 'paid',
    notes: 'Office dedicated IP line and staging server.',
    createdAt: '2026-08-05T11:00:00.000Z',
    updatedAt: '2026-08-05T11:00:00.000Z',
  },
  {
    id: 'exp-2026-006',
    title: 'Client Pitch Meeting Lunch & Team Coffee',
    category: 'food',
    amount: 7800,
    currency: { symbol: '৳', code: 'BDT', name: 'Bangladeshi Taka' },
    date: '2026-08-15',
    payeeVendor: 'Gloria Jeans Banani',
    paymentMethod: 'card',
    status: 'paid',
    notes: 'Strategy pitch meeting with Shwapno executives.',
    createdAt: '2026-08-15T15:00:00.000Z',
    updatedAt: '2026-08-15T15:00:00.000Z',
  },
  {
    id: 'exp-2026-007',
    title: 'Studio Lighting Rig & Audio Microphone Accessories',
    category: 'hardware',
    amount: 24500,
    currency: { symbol: '৳', code: 'BDT', name: 'Bangladeshi Taka' },
    date: '2026-08-17',
    payeeVendor: 'Camera Bazaar Multiplan',
    paymentMethod: 'bank',
    status: 'pending',
    notes: 'Pending final invoice receipt from supplier.',
    createdAt: '2026-08-17T14:00:00.000Z',
    updatedAt: '2026-08-17T14:00:00.000Z',
  },
];

export const SUPPORTED_CURRENCIES = [
  { symbol: '৳', code: 'BDT', name: 'Bangladeshi Taka' },
  { symbol: '$', code: 'USD', name: 'US Dollar' },
  { symbol: '€', code: 'EUR', name: 'Euro' },
  { symbol: '£', code: 'GBP', name: 'British Pound' },
  { symbol: '₹', code: 'INR', name: 'Indian Rupee' },
  { symbol: 'AED', code: 'AED', name: 'UAE Dirham' },
  { symbol: 'CAD', code: 'CAD', name: 'Canadian Dollar' },
  { symbol: 'AUD', code: 'AUD', name: 'Australian Dollar' },
  { symbol: 'SGD', code: 'SGD', name: 'Singapore Dollar' },
];

